### ISSUE TITLE
Points simply not being displayed 

### ISSUE THREAD

**Issue by jingyibo123** [jbehley/point_labeler#11]
Hi everyone,

First of all, congratulations on the great work and many thanks for sharing it!

While trying to import data into the labeler, part of the points are missing.

from semantic-kitti-api visualization tool
![Screenshot from 2019-12-27 15-04-51](https://user-images.githubusercontent.com/6594022/71506115-9b22d200-28ba-11ea-9d93-6b8b0444050c.png)

Visualization in the labeler, notice the diamond-shaped hole on the ground...

![Screenshot from 2019-12-27 15-02-24](https://user-images.githubusercontent.com/6594022/71506130-abd34800-28ba-11ea-8644-fe26adf24d70.png)

The missing part seen in the visualization tool

![Screenshot from 2019-12-27 15-02-35](https://user-images.githubusercontent.com/6594022/71506150-b68ddd00-28ba-11ea-953f-62677baada86.png)

I've narrowed down to the 1 scan and the points that are missing, but I don't see anything abnormal from the MainFrame.cpp...

Could anyone give me some hint/guess/idea on solving the problem?

Thanks a lot.

I attached the binary velodyne file and pose.txt, calib.txt here in case anyone need them to reproduce the problem [missing_points.zip](https://github.com/jbehley/point_labeler/files/4004601/missing_points.zip) .

The settings.cfg used:
```
tile size: 300
max scans: 400
min range: 0.0
max range: 200
gpu memory: 4
```

**Comment by jbehley** [comment]
For the KITTI dataset, we removed for each scan the points on the car. And this is a fixed size bounding box.

It might be that you have to turn off this by activating "add car points" under the visual options.  If you the change the tile it should now show all points.

**Comment by jingyibo123** [comment]
Thanks for the super fast response! 
It makes a lot sense judging from the shape and the orientation !
However checking "add car points" and changing the tile doesnot recover the missing points, not even checking the box and reopening the dataset.

Could you possibly indicate where the bounding box is defined?

**Comment by jbehley** [comment]
I will have a look, since the checkbox should have an effect.

the point removal is happening in a shader: https://github.com/jbehley/point_labeler/blob/769c060138cf091132e01eba348cd457c450c0a8/src/shaders/fill_tile_points.vert#L40

you can remove the line. I will later see what does not work there.

**Comment by jbehley** [comment]
Hi @jingyibo123,

I finally investigated the bug and the checkbox was actually not working. I think I broke the code at some point in time.

I fixed the issue and now the checkbox should have an effect. (You can see the effect also by reloading the scan or by changing the tile.)

For convenience, I just added also an option to the `settings.cfg`: `add car points: true`, which activates the option at startup and therefore you don't have to activate it all the time.

Does this finally resolve your problem?

**Comment by jingyibo123** [comment]
Thanks so much @jbehley, that totally solved the problem! 
I'll close the issue.
