### ISSUE TITLE
What does each column mean which in poses.txt file

### ISSUE THREAD

**Issue by hnsywangxin** [jbehley/point_labeler#12]
@jbehley @ben300694
Hello
I want to make my custom dataset through your annotation tools. Now, I have know how to generate the .bin files, but I don’t understand the file format of pose.txt.

What does each column mean which in poses.txt file

Can you give me a description such as "Each .bin scan is a list of float32 points in [x,y,z,remission] format"
Thank you very much!

**Comment by hnsywangxin** [comment]
I guess these 12 columns constitute the transformation matrix(3x4). The first column corresponds to the index (0,0), and the last column corresponds to the index (2,3).
Is this the case?
Thank you !

**Comment by jbehley** [comment]
Hello @hnsywangxin,

the format corresponds to the same format as the KITTI Odometry format (see also the devkit of the KITTI Odometry Benchmark for further details) , i.e., it's the 3x4 part of a 4x4 homogeneous transformation. The order is (0,0) (0,1) (0,2) (0,3) (1,0) (1,1) ...

Note that in the original KITTI all poses are given in the reference frame of a camera and therefore one has to transform the poses. (therefore the `calib.txt` is needed)

If you directly want to use the pose of the sensor you can simply set all poses to identity in your `calib.txt`.

**Comment by jbehley** [comment]
PS: Something like this here: https://github.com/jbehley/point_labeler/blob/769c060138cf091132e01eba348cd457c450c0a8/scripts/kitti_raw2odometry.py#L159-L165

**Comment by hnsywangxin** [comment]
Thank you for your help,  I will study the code carefully
