### ISSUE TITLE
Portability on Windows OS

### ISSUE THREAD

**Issue by jingyibo123** [jbehley/point_labeler#13]
Hi everyone,

First of all, congratulations on the great work and many thanks for sharing it!

The question is in the topic: could anyone elaborate on the portability on Windows?

**Comment by jbehley** [comment]
I cannot say anything about Windows. From a dependency side, I don't use very exotic stuff; thus, I expect that it should be possible. (But I never tried.)

Let me know if you manage to get it build under Windows.

**Comment by ncamous** [comment]
Hello, 

Thank you for putting at disposition this powerfool tool! 

I was wondering if are there any updates regarding the build on Windows? I have tried yet encountered some issues with catkin. 

Thanks in advance

**Comment by jbehley** [comment]
catkin is only used to get the dependencies (mainly glow); you can also install everything and just use CMake to build it. But I never tried it under windows.

**Comment by jingyibo123** [comment]
I was able to compile both glow and point_labeler on Windows10 64 bit with mingw64, with mostly cmake adaptation and compeletion, BUT with mingw64 7.3.0 and Qt5.13 the labeler is showing weird layout (image below)
![image](https://user-images.githubusercontent.com/6594022/77888805-69494f00-729f-11ea-9de7-0394908dfc02.png)

After switching to vs2013 and the layout becomes correct..
Seems like there's an issue of Qt between different compiler versions

**Comment by rancheng** [comment]
![plabeler_ui1](https://user-images.githubusercontent.com/2719771/79693634-b5056d80-8239-11ea-908b-6e84d1f2e5ff.PNG)

I build them with mingw64 but still, the large margin on top exists, I reckon it could be the QGLWidget related problem, since this class was depreciated for a while, I'll try to build it against QT 5.3 or earlier version to see if it works.

**Comment by rancheng** [comment]
![horizontal_plabeler](https://user-images.githubusercontent.com/2719771/79693827-f21e2f80-823a-11ea-9a9b-277162914e25.PNG)

When I change the layout outside the `mViewPortXYZ` into `QHBoxLayout`, it immediately shift the margin to the left...

```xml
<layout class="QVBoxLayout" name="horizontalLayout">
    <item>
     <layout class="QHBoxLayout" name="verticalLayout">
      <item>
       <widget class="Viewport" name="mViewportXYZ" native="true">
        <property name="sizePolicy">
         <sizepolicy hsizetype="MinimumExpanding" vsizetype="MinimumExpanding">
```
