### ISSUE TITLE
Unable to open few blocks using the tool

### ISSUE THREAD

**Issue by saishankarn** [jbehley/point_labeler#14]
Thank you for this amazing point cloud labeling tool. I am trying to use the tool to label roads in kitti raw sequences. I have converted the raw sequences to odometry like sequences using your conversion code. However, for few raw sequences, I am unable to open particular blocks. The tool closes automatically showing a segmentation fault. Can you please help me with this?

**Comment by jbehley** [comment]
Could you please say which raw sequence causes the error?

**Comment by saishankarn** [comment]
2011_09_26_drive_0022_sync, 2011_09_26_drive_0064_sync, 2011_09_26_drive_0070_sync, 2011_09_26_drive_0079_sync

**Comment by jbehley** [comment]
sorry for the delay, but recently was simply too much happening and I could now try at least the first sequence:

![image](https://user-images.githubusercontent.com/11506664/76368346-352dde80-6330-11ea-9c03-2bf292260eab.png)

I tried sequence `2011_09_26_drive_0022_sync` and as you can see it loads correctly after using the conversions script (`kitti_raw2odometry.py` in the scripts folder). That there are "empty" tiles is normal as I just approximate the coverage with scans.

**Comment by jbehley** [comment]
I close this issue for now. If you still have problems or could specifically report a sequence or case I will try to investigate it.
