### ISSUE TITLE
Label structure

### ISSUE THREAD

**Issue by discretecoder** [jbehley/point_labeler#16]
Hi, thanks for the great work. 
what is the label structure that is used? is it XYZRGBL format?

**Comment by jbehley** [comment]
For each scan, e.g., `00001.bin`, `00010.bin`, we have a `00001.label`, `00010.label` file. The labels in the file are stored in binary format using unsigned int with 32 bits (`uint32_t`).

See also http://www.semantic-kitti.org/dataset.html#format under **Semantic Segmentation**.

**Comment by jbehley** [comment]
did my answer solve your problem?

**Comment by jbehley** [comment]
seems to be solved?
