### ISSUE TITLE
Labeling Instances

### ISSUE THREAD

**Issue by Soini3913** [jbehley/point_labeler#17]
Hi,

First of all: Thanks for the nice tool!

I wanted to label some date of the KITTI-Dataset of the section Person. Now i ran into the Problem: How can i label instances of personen/objects? Is there some kind of tutorial?

Thanks!

**Comment by jbehley** [comment]
Thanks for your interest in the tool.

To label instances you have first to label the class. Then under instances, you can press "create" and select an area for which the instance should be created. If the points in the selected area are "instanceable", you will create a new instance.

There is also the option to split, remove, and join instances. Here, one has to first select an existing instance.

Currently, there is no video showing these options. If I find time, I might add some more descriptions and images to the wiki pages. However, there are currently some other more important things to do.

I hope the short description already helps.

**Comment by jbehley** [comment]
I close this issue now. Please, reopen it if you need further information.
