### ISSUE TITLE
build problem when runing 'catkin build point_labeler'

### ISSUE THREAD

**Issue by hahakid** [jbehley/point_labeler#20]
Sorry to bother you, I follow the instruction but fail at some point.
I am using ubuntu 16.04, as for the default python 2.7 may cause xml problem, and the current version of empy only support python>3.6, I update my default python to 3.6.
All things worked well until 'catkin build point_labeler'
here is what I got:
Exception ignored in: <bound method BaseEventLoop.__del__ of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/trollius/base_events.py", line 395, in __del__
  File "/usr/local/lib/python3.6/dist-packages/trollius/unix_events.py", line 65, in close
  File "/usr/local/lib/python3.6/dist-packages/trollius/unix_events.py", line 166, in remove_signal_handler
  File "/usr/lib/python3.6/signal.py", line 47, in signal
TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object

![Screenshot from 2020-04-22 19-36-47](https://user-images.githubusercontent.com/8140299/79977409-cf0cad80-84d0-11ea-9f5e-add7023ab4c4.png)
![Screenshot from 2020-04-22 19-37-03](https://user-images.githubusercontent.com/8140299/79977417-d2079e00-84d0-11ea-9f0b-9cc55ae16996.png)

I do have the empy installed as in pip list.
![Screenshot from 2020-04-22 19-37-29](https://user-images.githubusercontent.com/8140299/79977458-e21f7d80-84d0-11ea-9a5a-5aa4c247f862.png)
This is what shows during build

![Screenshot from 2020-04-22 19-37-44](https://user-images.githubusercontent.com/8140299/79977503-f2375d00-84d0-11ea-9a28-80e98c471f1d.png)
![Screenshot from 2020-04-22 19-38-01](https://user-images.githubusercontent.com/8140299/79977517-f794a780-84d0-11ea-8d62-2cbbb992a8c8.png)

**Comment by jbehley** [comment]
Just ignore this error at the end. Its important that there is written "3 packages successfully build"

In the `src/point_labeler/bin` should be the executable.

**Comment by hahakid** [comment]
Thanks, It can work right now.
