### ISSUE TITLE
Folder example

### ISSUE THREAD

**Issue by AinaHub** [jbehley/point_labeler#22]
Hi everyone,

First of all, i really appreciate your great work.
This isn't really an issue, but I was just wondering if someone can give me an example of the dataset cause I can't figure out the structure of every data in the sequence folder, especially the calib.txt and the poses.txt

Thank you for answering :)

**Comment by jbehley** [comment]
a point cloud folder should contain at least an `velodyne` folder with M files that have a `.bin` extension for M point clouds and that contains each N_t tuples of x,y,z,remission representing N_t points for each timestep. (In KITTI the point clouds have filenames of the format 00000.bin, 00001.bin, ...)

For each of the M point clouds, the program expects poses represented as row-wise homogeneous matrices T, i.e., each line is given by "T(0,0), T(0,1) T(0,2) ... T(3,3)"

The calibration file contains 5 calibration matrices in the same format as the poses. Here you can find more information in the KITTI Odometry dataset devkit readme file.

You can also consult our conversion script [1] to see the structure of the poses.txt and calib.txt.

The label folder is generated by the program and the image folder is optional.

[1] https://github.com/jbehley/point_labeler/blob/master/scripts/kitti_raw2odometry.py

**Comment by AinaHub** [comment]
Hi Jens,
Thank you very much for your answer, now it work very well :D

Therefore i have some confusion or question if it don't bother you :)
 - How can i add some specific label for the annotation (other than the
predefined)
 - Change the background to black
 - highlight a label when selected

i hope to hear from you soon :)

Best regards

**Comment by jbehley** [comment]
1. You have to modify the `labels.xml` in the bin folder; there you can modify the name, id, color, etc.
2. You have to change the clear color in the [Line 673](https://github.com/jbehley/point_labeler/blob/805a35ce6cc29e0daa95bd91ab375fb308007154/src/widget/Viewport.cpp#L673) into `glClearColor(0.0f, 0.0f, 0.0f, 0.0f)`.
3. I don't know what you mean and have currently no intention to implement additional functionality. But you can activate the filtering (hotkey <kbd>F</kbd>) and then click with <kbd>CTRL</kbd> pressed on a label button to select a label for filtering, which will remove the corresponding label from the view.

**Comment by AinaHub** [comment]
I really appreciate you taking the time to answer, it really help.

Best regards

**Comment by jbehley** [comment]
No updates for a while. Thus, I close this issue as it seems to be solved. If it still needs help, please re-open the issue. Thanks.
