### ISSUE TITLE
GUI of labeling disappeared

### ISSUE THREAD

**Issue by lisilin013** [jbehley/point_labeler#28]
Thanks for your great work!
**After building point_labeler, my gui like the following pictures**, then I don't know how to label my personal dataset. What is the problem?
![image](https://user-images.githubusercontent.com/20241934/95743292-1f1c3e00-0cc4-11eb-87e4-34cc513c97c3.png)
Thanks again!

**Comment by jbehley** [comment]
We only support point clouds in the KITTI format, i.e., your data should have a specific folder structure (see https://github.com/jbehley/point_labeler#folder-structure), poses in the poses.txt in the KITTI format and format of the point clouds, i.e., binary with float values. However, you can also rewrite the KITTIReader to read other point clouds.

I'm wondering that the icons are not shown and the labels.xml is not populating the label buttons. Ensure that you run the program from the bin folder inside the project folder, such that it can find the correct paths (which are relative to the bin folder).

**Comment by lisilin013** [comment]
Thank you very much for answering my question so quickly!


hmm, actually the reason cause some elements of gui disappeared is the following code in repo
```cpp
  std::string assertDir = QDir::currentPath().toStdString() + "/../assets/";
```
I run the following cmd in terminal, so I guess the code can not load these elements correctly.
```bash
./src/point_labeler/bin/labeler
```

Run this cmd, everything will be ok.
```bash
./labeler
```

**Comment by jbehley** [comment]
Good, then everything works as expected? is the issue then solved?

**Comment by lisilin013** [comment]
Yes. Thanks very much.
