### ISSUE TITLE
Label Filtering

### ISSUE THREAD

**Issue by lisilin013** [jbehley/point_labeler#29]
When I press `ctrl+label`, I find that not all points I labeled will be filtered. There are still some points left there, which are not filtered.

- before filtering
![image](https://user-images.githubusercontent.com/20241934/95754875-4419ac80-0cd6-11eb-8254-c10cd303055c.png)
- after filtering
![image](https://user-images.githubusercontent.com/20241934/95754958-5c89c700-0cd6-11eb-8c4a-50480245e555.png)

**There are three kinds of object are red, but I am sure that I only labeled one of them**, which is person(red).
![image](https://user-images.githubusercontent.com/20241934/95755144-9fe43580-0cd6-11eb-8ef6-b24aae2073d3.png)

**Comment by jbehley** [comment]
Please note the difference between "moving" and "static" persons. And check if the label is maybe "outlier", wich is also read. You can also filter multiple categories.

**Comment by lisilin013** [comment]
Oh, got it.
I labeled the person two kinds of labels("moving" and "static"), but I just filtered moving person.

Thanks a lot!
