### ISSUE TITLE
Folder structure supports KiTTI data forder?

### ISSUE THREAD

**Issue by Durant35** [jbehley/point_labeler#3]
+ KiTTI data forder after uncompression couldn't be opened by this labeler
![image](https://user-images.githubusercontent.com/6770853/63265114-632dd180-c2bf-11e9-9387-ea520387bfec.png)

**Comment by jbehley** [comment]
Hi @Durant35,

we currently only natively support the folder structure of the KITTI Odometry Benchmark. If you want to use right away the tool, you have to convert the folder structure into this format.

However, I put together a script that will take care of this and turn a "raw" dataset into an "odometry-like" dataset, see [kitti_raw2odometry.py](https://github.com/jbehley/point_labeler/blob/master/scripts/kitti_raw2odometry.py)

![image](https://user-images.githubusercontent.com/11506664/63273582-85fbbe00-c29e-11e9-93d0-266be618475e.png)

Your can use `./kitti_raw2odometry.py <input> [output]`, where <input> correspond to the input raw directory containing an `images_02`, `oxts`, and `velodyne_points` folder. The script will either create an output folder at `output` or if you omit this it will just take the name of `input` and create a local folder with that name. The script creates an `images_2` and `velodyne` folder and furthermore  `calib.txt` and `poses.txt.

![image](https://user-images.githubusercontent.com/11506664/63273456-446b1300-c29e-11e9-8570-9962ae43b1b3.png)


Hope that helps.

**Comment by Durant35** [comment]
It works, thus close this issue.
BTW, hope to see a demo video for tool use, mostly how to label...
