### ISSUE TITLE
catkin init issue

### ISSUE THREAD

**Issue by BizuK95** [jbehley/point_labeler#32]
Hi,
I have followed your guide for builiding and downloading the dependencies, and I am stuck on the following error:

WARNING: Your workspace is not extending any other result
space, but it is set to use a `linked` devel space layout.
This requires the `catkin` CMake package in your source
space in order to be built.

I am assuming that I need to build first a workpsace the relies on ros/catkin but I am having problems building that too.

The main error I am receiving is when I run "catkin deps fetch" and I receive 
"INFO:deps: Avoid fetching ROS packages.
INFO:deps: [ROS]: Searching all packages.
INFO:deps: [ROS]: Not found. Ignoring pre-defined ROS packages.
INFO:deps: Searching for dependencies."

Do you have any idea how to continue from here?
Help would be appreciated.

**Comment by jbehley** [comment]
Sorry for the late reply. You can setup a proper workspace with the following commands:

`cd
mkdir catkin_ws
cd catkin_ws
mkdir src
catkin init
cd src
git clone https://github.com/ros/catkin.git`

then the needed packages should be found. Ensure that you also get the other dependencies, like catkin_fetch.

**Comment by beepbeep08** [comment]
hello i try that, but commands not working, help me plz. @jbehley

**Comment by jbehley** [comment]
@beepbeep08 what is exactly not working? catkin? where does it fail?

**Comment by swLeeinTestworks** [comment]
I'd got the same problem, before changing the default python in ubuntu 18.04.

Why don't you change your default python from python2.7 to python3.6 temporary?


reference link : https://github.com/jbehley/point_labeler/issues/20

**Comment by jbehley** [comment]
as there is no further update on the issue, i will now close it.
