### ISSUE TITLE
my built version are different from pic on wiki,which i can't change the color of label.

### ISSUE THREAD

**Issue by hungkyun** [jbehley/point_labeler#33]
![2021-02-25 18-02-18屏幕截图](https://user-images.githubusercontent.com/39060527/109137091-ca212600-7793-11eb-92d9-a9be12582412.png)

**Comment by jbehley** [comment]
ensure that the `labels.xml` is either linked or copied into the `bin` folder. It also seems that the assets are not found. You should start the binary from the `bin` folder.

hope that resolves the issue.

**Comment by hungkyun** [comment]
i'm grateful for your helping!i solved it by coping the **assets** folder from the source code folder to the **src** folder (my version is built by catkin_make)

**Comment by hungkyun** [comment]
sorry to bother that i encountered some strange bug recently.after i open my custom data set i found a small square gap around (0,0,0) of the pointcloud displayed(i use other tools like vispy to check the raw bin file ).i try to change the “min range” in setting.cfg to 0.0 but it dosen't work out(i also try to make "min range" larger then it shows a greater circle gap,which shows that it performs circle like filtering).

is there any other possible place to change this? i do needs the points in the square gap。

**Comment by jbehley** [comment]
As KITTI has points from the car itself inside the LiDAR scans, we decided to remove these points inside a bounding box around the origin.

You can add the option `add car points: true` in the `settings.cfg`, then the points at the origin should be shown. I will update the `README.md` to include this setting.

**Comment by hungkyun** [comment]
Thank you for your enthusiastic replying！Since not all the vehicle have the same size of cars in kitty and some data is even collected by handheld LIDAR ,i think this will helps a lot.
