### ISSUE TITLE
About using point labeler for Point Cloud Based 3D Detection  

### ISSUE THREAD

**Issue by ArghyaChatterjee** [jbehley/point_labeler#34]
Hello, first of all, thanks for you tool. It is really wonderful and works great for semantic segmentation related task. But I was wondering can I use it for Point Cloud based 3D Detection? If yes, then can you explain the process briefly? If no, which one (github repo) do you suggest to label points for 3D point cloud based detection ? (3D bounding box / Point cloud Mask)

**Comment by jbehley** [comment]
My tool provides the possibility to also annotate instance for "instancable" classes (an option in `labels.xml`) that provides at least you mentioned point masks.

Regarding bounding box annotation, I did not explicitly used a tool or can recommend something.

**Comment by jbehley** [comment]
the labels are stored as binary, thus, there is no way to opening them in a text editor.

you can use, for instance, numpy to open the file and see the contents:

```python
>>> import numpy
>>> labels = np.fromfile("path\to\label\00000.label", dtype=np.int32)
>>> print(labels)
```

hope that solves your issue.

**Comment by ArghyaChatterjee** [comment]
Thanks. It worked !! 
```
$ python
>>> import numpy as np
>>> labels = np.fromfile("path/to/labels/000000.label", dtype=np.int32)
>>> print(labels)
```
