### ISSUE TITLE
Spinning icon when trying to load test data

### ISSUE THREAD

**Issue by rhitti** [jbehley/point_labeler#36]
Hello, first of all I wanna say this is a fantastic product!!
I looked at the documentation closely and really like what you built!

I wanted to try it out on my machine, but get a beachball that loads forever.
I am using 140mb of assets from the SemanticKITTI (the first 98 frames from the 00 folder, along with all the rest).

Am I doing something wrong?
It seems to be staying in that state forever.

Thanks!
![Screen Shot 2021-04-01 at 8 36 15 AM](https://user-images.githubusercontent.com/56643887/113295114-c5d1b680-92c5-11eb-95c6-f1bffcb7b47b.png)

**Comment by rhitti** [comment]
That's what my folder structure looks like
![Screen Shot 2021-04-01 at 8 43 32 AM](https://user-images.githubusercontent.com/56643887/113295583-61fbbd80-92c6-11eb-83a8-dd0a36018149.png)

**Comment by jbehley** [comment]
If you want to use less than the original number of files, you have to also edit the poses.txt to only have the corresponding number of lines. Based on the poses I compute the number of tiles and the indexes of scans per tiles. Thus, in your case, the program tries to access filenames at probably out of vector bounds locations (based on the indexes), which were never initialized. That the program did not produce a segmentation fault is somehow pure luck.

Anyway, you need to modify the "poses.txt" if you want to use fewer scans.

If you just want to test it with few scans, then I would suggest taking sequence 04 (which has only 271 scans.)

**Comment by rhitti** [comment]
Thank you for the quick reply ⚡ 

I will try this now with sequence 04.  Clear answer, should be able to figure it out :)

**Comment by rhitti** [comment]
Thank you so much Jens!
Your recommendation worked perfectly, closing this issue!

Might be useful for others in the future.  Just load sequence 04.
