### ISSUE TITLE
Weird mainframe window size issue [followed installation instruction and no code change]

### ISSUE THREAD

**Issue by chenzeh** [jbehley/point_labeler#37]
Hi, thank you for your excellent work, this project is amazing.
I recently install the point_labeler and found the UI setting looks weird, I only have the half height of view window. (the issue is shown as following)
![Screenshot from 2021-04-12 17-26-58](https://user-images.githubusercontent.com/82355019/114372589-5062c180-9bb4-11eb-80d9-b1f957f392b1.png)

I almost strictly follow the instruction you provided in README, and I never change any cfg. Do anyone have this similar issue? And could you please help me to find some clue to fix this issue, thank you.

**Comment by jbehley** [comment]
it might be an issue with the Qt version, that there changed something. Can you check which version of Qt you have? I never saw this effect before.

**Comment by chenzeh** [comment]
> it might be an issue with the Qt version, that there changed something. Can you check which version of Qt you have? I never saw this effect before.

I believe this is the qt version I have:  qt5-default:amd64 (5.12.8+dfsg-0ubuntu1)

**Comment by jbehley** [comment]
I have to investigate issue. resizing the window does not resolve it?

Sorry for the delay. I'm currently busy with more time-critical tasks. :/

**Comment by daanbl** [comment]
I can confirm this issue on Ubuntu 20.04 with QT version 5.12.8. Resizing does not have an effect.

**Comment by jbehley** [comment]
okay. I now also see the problem under Ubuntu 20.04. (the catkin workflow is also a bit broken now...hmmm)

I have to investigate what is wrong here, but it will take a bit until I have time...sorry.

**Comment by jbehley** [comment]
Just a small update: I unfortunately could find time to investigate this more. A quick fix with replacing the "old" QGlWidget with an modern QOpenGLWidget did not help and lead to some issues with the initialization of the OpenGL context.

Unfortunately, right now the labeler is broken on Ubuntu 20.04 and my quick fix would be to have an Ubuntu 18.04 currently to run it.

I hope I have more time next month to work on this more, but currently there are teaching duties that need basically all my time. :/

**Comment by jbehley** [comment]
I finally found the problem. with the new version it should work as intended also in Ubuntu 20.04. If you face this problem in the future, then just re-open the issue.
