### ISSUE TITLE
Unable to open label file

### ISSUE THREAD

**Issue by songyongkang** [jbehley/point_labeler#38]
-- Setting 'tile size' to 100
mem size: 2400 MB
-- Setting 'max scans' to 500
-- Setting 'min range' to 2.5
-- Setting 'max range' to 50
/home/qiaran/catkin_ws/src/point_labeler/bin
[ERROR] velodyne or poses.txt missing.
#tiles  = 40
Reading instances.txt...finished.
Unable to open label file. 
Unable to open label file. 
[1]    15795 segmentation fault  sudo ./labeler

**Comment by songyongkang** [comment]
I've solved it.
It is my dataset problem.

**Comment by sammilei** [comment]
@songyongkang How did you get it solved?
