### ISSUE TITLE
Toggling between annotated classes and remission values

### ISSUE THREAD

**Issue by SvenMuc** [jbehley/point_labeler#39]
Hi,

I'm currently planning to annotate additional datasets. Is there a possibility to switch view between the remission values and annotated classed.

**Example:**
I already annotated a couple of point clouds. Some days later, I'd like to review the annotation quality. For this it is sometimes helpful to switch between the remission values and annotations classes. Currently it seems to be blended.

Furthermore, it would be nice to visualize the point cloud in the image view. Is, there a way to realize it?

Thanks!

**Comment by jbehley** [comment]
Thanks for your interest in our tool:

1. and 2. These functionality is currently not supported. but it should not be hard to realize something like this. I'm currently busy with more urgent things and therefore cannot promise to do there something in the next weeks.

**Comment by SvenMuc** [comment]
I managed it to implement the first topic (toggling between remission and label).
I'll try the second as well, when I find some more time.

Thanks!

**Comment by jbehley** [comment]
that's great. hope then your annotation goes now smoothly. :)
