### ISSUE TITLE
 not show the point cloud.

### ISSUE THREAD

**Issue by shengyuwoo** [jbehley/point_labeler#4]
Is the data of annotated point cloud KITTI? I configure it, the software can be opened, but the point cloud can not be loaded, and the interface does not show the point cloud. Is it because my data catalog is not set correctly? How to set it up?

**Comment by jbehley** [comment]
Hi @shengyuwoo,

if you downloaded our data and  put it in the correct folder structure, you should be to open it (note you have to select the root folder to open the data). You need at lease a `velodyne` folder containing the `.bin` files, a `poses.txt`, and a `calib.txt`. All this is provided if you follow the download instructions on http://www.semantic-kitti.org/dataset.html#download

If you want to use for instance some sequence from the KITTI raw data (http://www.cvlibs.net/datasets/kitti/raw_data.php), you have to get the data into the right folder structure and format. We provide a converter that moves all data in the correct folders and creates the `poses.txt` and `calib.txt` needed (see [kitti_raw2odometry.py](https://github.com/jbehley/point_labeler/blob/master/scripts/kitti_raw2odometry.py))

If you want to use your own data, you have to either get it into the right format or modify the code accordingly.


Hope that helps.

**Comment by shengyuwoo** [comment]
> Hi @shengyuwoo,
> 
> if you downloaded our data and put it in the correct folder structure, you should be able to open it (note you have to select the root folder to open the data). You need at least a `velodyne` folder containing the `.bin` files, a `poses.txt`, and a `calib.txt`. All this is provided if you follow the download instructions on http://www.semantic-kitti.org/dataset.html#download
> 
> If you want to use for instance some sequence from the KITTI raw data (http://www.cvlibs.net/datasets/kitti/raw_data.php), you have to get the data into the right folder structure and format. We provide a converter that moves all data in the correct folders and creates the `poses.txt` and `calib.txt` needed (see [kitti_raw2odometry.py](https://github.com/jbehley/point_labeler/blob/master/scripts/kitti_raw2odometry.py))
> 
> If you want to use your own data, you have to either get it into the right format or modify the code accordingly.
> 
> Hope that helps.

oh, thank you very much.

**Comment by jbehley** [comment]
I close this issue for now. If you need further assistance, please reopen the issue. thanks.
