### ISSUE TITLE
Save the divided tiles from whole scequence with overlapping scanes

### ISSUE THREAD

**Issue by Hao-HUST** [jbehley/point_labeler#40]
Hi, I noticed that the sequence is divided into different tiles on your labeling tool. Is that possible to separately save each tile with point cloud and labels?

**Comment by jbehley** [comment]
There is currently no option available for this. You can look in our code, how we achieve this using the given trajectory: https://github.com/jbehley/point_labeler/blob/35505715fe663e474f9ce749ee39e794c6bbefc2/src/widget/Viewport.cpp#L257-L410

But the process is quite simple (even though we use OpenGL to speed it up, you can replicate it in Python):
1. Determine Tile centers and corresponding indexes of point clouds based on the trajectory. We use a simple heuristic to determine all point clouds that overlap: https://github.com/jbehley/point_labeler/blob/35505715fe663e474f9ce749ee39e794c6bbefc2/src/widget/KittiReader.cpp#L73-L172
2. Using the indexes you can now open the point cloud files and copy the points accordingly. Depending on the center and the extent of the tile, it is possible to determine which points should go in.

I hope this helps (even though quite late now. Sorry again...)

**Comment by jbehley** [comment]
There has been no further activity here, therefore, I am closing the issue now. Please re-open the issue if you have further questions.
