### ISSUE TITLE
Messy points appear when reopen labeled data 

### ISSUE THREAD

**Issue by shuangjiexu** [jbehley/point_labeler#41]
Thank you very much for your open-source tools.
I'm currently annotating my own datasets, but find some strange issues. In some sequence, the labeled data will be a mess when reopen (like the figure below, some labeled road/car points are shown in other place).
![github_issue](https://user-images.githubusercontent.com/10096172/117913091-4d720280-b313-11eb-8ff3-4559f7818fc9.png)
We annotate data on Ubuntu 16.04, with 4G memory and HD630 Integrated Graphics. OpenGL version 3.0 Mesa 18.0.5 and core profile version string is 4.5.
I don't know if there is something missing in my environment or there is another mistake somewhere that I cannot find.

Thank you in advance for your help!

**Comment by jbehley** [comment]
Sorry for the late reply, very busy currently. :/

I currently don't know what happens there. Which points you mean specifically? Can you show the same scan before and after reopening?

We use the labeler mainly in Ubunut 18.04 and did not encounter issues.

**Comment by hahakid** [comment]
I face the same problem, and corrected following [https://github.com/jbehley/point_labeler/issues/11](url),
you can check by selecting "show single scan", to see if the center of the current point cloud is missing with a rectangle.

**Comment by jbehley** [comment]
Do you have individual scans (say around 150k points) or larger scans/a single large scan (say millions of points) that yo want to annotate?

**Comment by hahakid** [comment]
> Do you have individual scans (say around 150k points) or larger scans/a single large scan (say millions of points) that yo want to annotate?

I don't have a lidar like that, but I can merge several frames as one file and import into the tool. And the merged map can also achieve this scale of points. But what do you mean by that?

**Comment by jbehley** [comment]
We observed some problems with very large point clouds (20 million+); thus I was wondering.

Could you provide an image or a link to the data to better understand what is the problem?

**Comment by hahakid** [comment]
@jbehley 
![ScreenCapture_2023-03-04-08-18-59](https://user-images.githubusercontent.com/8140299/223013143-936ed3db-fc35-42c8-af91-4556fab70d82.png)
the black (unlabeled points) are filtered by ego-car bounding box. I think we are not talking about the same problem.
![garage](https://user-images.githubusercontent.com/8140299/223013154-8bdc5210-15d8-48a1-a41d-29ce6fd016e6.png)

I never processed map with too huge points.  but when handling huge maps, I use small cells. the below image is 17 million.
<img width="1063" alt="1678073599868" src="https://user-images.githubusercontent.com/8140299/223013621-20f737b8-f055-4e1a-bb54-4d24d1032498.png">

**Comment by jbehley** [comment]
not sure what one sees in the first image: are the black points the problem?

the points that get removed by the bounding box in the center of each scan, can be added by modifying the "settings.cfg":

`add car points: true`

**Comment by jbehley** [comment]
the issue seems to be resolved or simply abandoned; therefore, I simply close it now. Please re-open the issue if you have still concerns.
