### ISSUE TITLE
about calib.txt

### ISSUE THREAD

**Issue by xdtzzz** [jbehley/point_labeler#43]
hi, thanks for your amazing code!
i wonder if i test on my own lidar .bin files, i did't use camera, what should the calib.txt be written?

**Comment by jbehley** [comment]
sorry for the late reply, I'm currently very busy...

as in our raw2kitti_odometry script (see https://github.com/jbehley/point_labeler/blob/master/scripts/kitti_raw2odometry.py), you can basically write just identities there (code copied from the script):

```python
  # write dummy calibration file.
  # Note: the actual calibration should be irrelevant for our purposes, 
  # since we have poses in the Velodyne coordinate system.
  # if you want to have the "real" thing, one has to transform the poses 
  # into the camera coordinate system via Tr.
   
   calib_file = open(os.path.join(output_folder, "calib.txt"), "w")
   calib_file.write("P0: 1 0 0 0 0 1 0 0 0 0 1 0\n")
   calib_file.write("P1: 1 0 0 0 0 1 0 0 0 0 1 0\n")
   calib_file.write("P2: 1 0 0 0 0 1 0 0 0 0 1 0\n")
   calib_file.write("P3: 1 0 0 0 0 1 0 0 0 0 1 0\n")
   calib_file.write("Tr: 1 0 0 0 0 1 0 0 0 0 1 0\n")
   calib_file.close()```

**Comment by jbehley** [comment]
as there seems no issue with this anymore, I close the issue. feel free to reopen the issue again if you still have problems.
