### ISSUE TITLE
The X11 connection broke: No error (code  0)

### ISSUE THREAD

**Issue by Chuanyu-LD** [jbehley/point_labeler#53]
Dear authors,

thank you for your excellent work. 

when i run the bin/labeler, the xserver raise the error

```
The X11 connection broke: No error (code  0)
XIO: fatal IO error 22 (invalid argument) on X server ":1"
after 526 requests (526 known processed) with 0 events remaining
```
The Dependencies are all installed.

The ubuntu is 18.04, OpenGL version is 4.6.0, and NVIDIA driver is 470.57.02, GPU Quadro P620, only 1 Screen.

What I tried:
export DISPLAY=:0
or export DISPLAY=:0.0
or export DISPLAY=:1.0

All not work.

The commands
`xclock`
works (suggests Xorg works?)

One guess is the multi threads usage in labeler codes? But the software runs well on the other computer.

**Comment by jbehley** [comment]
sorry I have no idea and never observer this issue. Hope you could resolve it by now.

**Comment by Chuanyu-LD** [comment]
Environment problem. Recompiled is okay. Anyway thanks
