### ISSUE TITLE
Adding additional labels

### ISSUE THREAD

**Issue by Nihar-Bagewadi** [jbehley/point_labeler#54]
Hello, Thank you for this much needed tool.  I see that we can have semantic and instance labels for the same point. for e.g. the car has both semantic and instance labels. I wanted to know if we can have another type of label for the same point. Let's say we can have part labels as well? such as a point belonging to car will have semantic, instance and also part labels?. If I create a new label such as wheels and label the wheels of car. I fear it will overwrite the existing labels. and the semantic and instance labels will be lost.

**Comment by jbehley** [comment]
multiple labels are currently not supported. currently the only way would be to have a copy of the original labels, then annotate your additional parts, and then later join them again. (combining the original labels with labeled parts...)
