### ISSUE TITLE
Can't this project be run with CMake alone?

### ISSUE THREAD

**Issue by DonghunP** [jbehley/point_labeler#55]
Thanks for amazing project.

I just wonder why can't this project execute CMake alone?

because, I met some error while using custom .bin file and I want to debug it using IntelliJ CMakeproject.

Thanks

**Comment by jbehley** [comment]
the way we do it has some historical reasons and using catkin helped with making the shared libraries available. technically, you could also rewrite the cmakefile such that it compile with "pure" cmake, but it's nothing I want to do now.

The way I use it is via the generated Makefiles in the build directory in Eclipse. Maybe you can setup IntelliJ to take just the Makefile?
