### ISSUE TITLE
problem with catkin deps fetch 

### ISSUE THREAD

**Issue by medif** [jbehley/point_labeler#6]
i am using Ubuntu 18.04.3 LTS, i just followed the mentioned instructions and i had this error :
![Screenshot from 2019-09-26 19-00-52](https://user-images.githubusercontent.com/55558657/65730522-0aa4dd80-e090-11e9-9521-3b51a4649510.png)

i made the update but i got the same error. any help will be appreciated.
Thank you

**Comment by jbehley** [comment]
You can also get the needed package using `git clone`:

In the `catkin_ws/src` folder:
`git clone https://github.com/jbehley/glow.git`

This should create a folder named `glow` in your src directory.

Then you should be able to build with `catkin build`.

**Comment by medif** [comment]
thank you for your response. it ceated the glow folder But i just got the same error again when i making catkin build and it did not generate the Bin folder.
![Screenshot from 2019-09-26 21-27-57](https://user-images.githubusercontent.com/55558657/65735331-eacbe480-e0a4-11e9-9f72-0aa5dac1527a.png)

**Comment by jbehley** [comment]
Did you follow the instructions from the error message?

It seems that `catkin_tools` is outdated. Please follow the instructions on https://catkin-tools.readthedocs.io/en/latest/installing.html to get a version that can handle the particular version of the `package.xml`.

Sorry that I can't give you more specific instructions.

**Comment by medif** [comment]
Thank you for your response, i installed catkin tool fetch, it solved the error, but did not generate the bin file in the point_labeler, i got this :
![Screenshot from 2019-10-02 18-07-54](https://user-images.githubusercontent.com/55558657/66085694-ee95b600-e53f-11e9-937d-64e5b33c0e7e.png)

**Comment by medif** [comment]
thank you for your response, i resolved the problem but when running the labeler i got another issue 
![Screenshot from 2019-10-02 21-11-08](https://user-images.githubusercontent.com/55558657/66092257-599fb680-e559-11e9-91c0-74e7663c03fa.png)

**Comment by jbehley** [comment]
Seems to be a graphics driver issue with the nouveau driver. Please use the official nvidia driver for your graphics card that should resolve the problem.

**Comment by medif** [comment]
HI, 
I have question about the point cloud of semantic-kitti, Can i add some labels to other structure in the class building, I mean is it possible to label the doors for example, because i need some classes under the class building.
Thank you so much for your response

**Comment by jbehley** [comment]
@medif it seems like that you were now able to get the program running. 

Since the last problem is not related to this issue I created a new issue #7. Please find an answer to this question in the new issue.

I close the issue now. If you have additional problems. Please reopen this issue or create a new issue. Thanks.
