### ISSUE TITLE
How to enable the CAD navigation mode?

### ISSUE THREAD

**Issue by Freddd13** [jbehley/point_labeler#61]
Firstly, thanks for your awesome work.
I was using the labeler to annotate my own poincloud dataset. However I was used to the navigation logic in RVIZ(in ros). It was quite painful to use the default mouse moving strategy. I found a "CAD mode" in the wiki. Maybe that should be what I want?
I wonder how can I switch to this mode? Thank you!

**Comment by Freddd13** [comment]
Solved by modifying the CAD mode in the source code.

**Comment by Irving87** [comment]
在菜单栏里面的view->camera里面有选CAD模式，不过移动起来也很费劲，请问你是修改哪里的代码，我也想修改一下这个移动的方式速度之类的

**Comment by Freddd13** [comment]
> 在菜单栏里面的view->camera里面有选CAD模式，不过移动起来也很费劲，请问你是修改哪里的代码，我也想修改一下这个移动的方式速度之类的

我没改速度，好像只是把移动改成鼠标右键了，记不清了，你可以看看我改完的 https://github.com/Freddd13/point_labeler，但是当时这个版本是改完强制push的，可能看不到git记录…

**Comment by Freddd13** [comment]
> why translation in cad mode is not work?

Where did you select the CAD? There's no CAD in my view menu, thus I modified he CAD in one class constructor in the code and recompiled it. I had no problem translating.

**Comment by Freddd13** [comment]
> > why translation in cad mode is not work?
> 
> Where did you select the CAD? There's a CAD in my view menu, thus I modified the CAD in one class constructor in the code and recompiled it. I had no problem translating. Maybe you didn't press ctrl?(I modified the hotkey)
