### ISSUE TITLE
Issue with open directory

### ISSUE THREAD

**Issue by completezealous** [jbehley/point_labeler#63]
When I ran the software and opened the file, there was a flash back,
**OpenGL Context Version 3.3 core profile
GLEW initialized.
OpenGL context version: 3.3
OpenGL vendor string  : VMware, Inc.
OpenGL renderer string: llvmpipe (LLVM 10.0.0, 256 bits)
temp mem size: 3.6 MB
Found 20 instanceable labels.
-- Setting 'tile size' to 100
mem size: 2400 MB
-- Setting 'max scans' to 500
-- Setting 'min range' to 2.5
-- Setting 'max range' to 100
/home/lk/catkin_ws/src/point_labeler/bin
Gtk-Message: 12:42:39.610: GtkDialog mapped without a transient parent. This is discouraged.
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::bad_lexical_cast> >'
  what():  bad lexical cast: source type value could not be interpreted as target
Aborted (core dumped)
**
I'm using semantikitti data set ,file structure the same as yours.
I need you help,Thanks!

**Comment by jbehley** [comment]
Sorry for the delay: Ensure that you always open the root directory of the dataset where the pose.txt is contained.

And ensure that your locale is en_US or similar, where the decimal point is "." and not "," like in German (and other languages?)

**Comment by Irving87** [comment]
> 

The same question, have you solve this problem?

**Comment by completezealous** [comment]
> > 
> 
> The same question, have you solve this problem?
没有  我换了一个账号解决了

**Comment by Irving87** [comment]
> > > 
> > 
> > 
> > The same question, have you solve this problem?
> > 没有  我换了一个账号解决了

https://github.com/jbehley/point_labeler/issues/67#issuecomment-1558412511

**Comment by completezealous** [comment]
> please check that you have a locale (such as en_US, where decimal points are represented by "."): See
> 
> https://www.thomas-krenn.com/en/wiki/Configure_Locales_in_Ubuntu

ok ,I will try
