### ISSUE TITLE
Plugin does not support setParent and propagateSizeHints()

### ISSUE THREAD

**Issue by Levino614** [jbehley/point_labeler#69]
Hi all, 

I'm currently facing an issue when trying to run the tool from WSL inside a docker container. I followed the ReadMe and I have all dependencies installed. When starting the tool, I receive follow output and the tool won't open:

**This plugin does not support setParent!**
OpenGL Context Version 5.0 core profile
GLEW initialized.
OpenGL context version: 4.5
OpenGL vendor string  : Mesa/X.org
OpenGL renderer string: llvmpipe (LLVM 15.0.7, 256 bits)
temp mem size: 3.6 MB
Found 20 instanceable labels.
-- Setting 'tile size' to 100
mem size: 2400 MB
-- Setting 'max scans' to 500
-- Setting 'min range' to 2.5
-- Setting 'max range' to 50
/root/catkin_ws/src/point_labeler/bin
**This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()**

I have a xfce4-session running in background. 

How can I troubleshoot this problem?

**Comment by jbehley** [comment]
sorry for the late reply. currently, I have no clue what could be wrong. but it seems like that the graphics driver is not a "normal" vendor like ATI or Nvidia. We run the program only under Ubuntu and therefore I cannot provide any support for windows.
