### ISSUE TITLE
Adding labels

### ISSUE THREAD

**Issue by jbehley** [jbehley/point_labeler#7]
HI, 
Can you give me instructions 
I have question about the point cloud of semantic-kitti, Can i add some labels to other structure in the class building, I mean is it possible to label the doors for example, because i need some classes under the class building.
Thank you so much for your response

_Originally posted by @medif in https://github.com/jbehley/point_labeler/issues/6#issuecomment-542485570_

**Comment by jbehley** [comment]
(@medif I opened this issue to have a better reference also for other people, since it might be relevant also for other people.)

Yes, it's possible to add classes. You have to modify the `labels.xml` file in the bin folder (which is a symbolic link to `assets/labels.xml`. This file is parsed by the labeling tool.

Add something like:

```xml
 	<label>
		<id>53</id>
		<name>door</name>
		<description>Doors inside a building</description>
		<color>255 0 255</color>
		<root>structure</root>
		<macro>structure</macro>
		<category>building</category>
	</label>
```

This creates a new button in the labeling tool with the specified color (here a pink button):

![image](https://user-images.githubusercontent.com/11506664/66890384-4a534b00-efe6-11e9-9924-c345e4935826.png)

**Comment by medif** [comment]
thank you so much ,
but is there any circumstance on the used data , i mean how many sequence should be used, used only the first sequence but i cannot move to make labels for the next doors.
and how to ensure that the labels are added on the point cloud.
Thank you

**Comment by jbehley** [comment]
Have also a look at the wiki (https://github.com/jbehley/point_labeler/wiki), which provides more information on the usage.

![image](https://raw.githubusercontent.com/wiki/jbehley/point_labeler/images/point_labeler_gui.png)

To change the tile, you have to use the tile selector (4). When you change the tile it will prompt to save the labels. But you can also use the "save button" (under 5) or <kbd>CTRL + S</kbd> to save the current tile. The labels are update in the `labels` folder of the opened sequence.

**Beware:** Once save there is now way back. You can only revert (the arrow in the toolbar under (5)) to the last saved state.


Is your issue with adding the labels solved?

**Comment by jbehley** [comment]
@medif is your issue solved?

**Comment by jbehley** [comment]
I close the issue now, since it seems to be no issue anymore.

You can reopen or add information if you need more assistence.
