### ISSUE TITLE
Cannot read my own dataset

### ISSUE THREAD

**Issue by PengKunPROO** [jbehley/point_labeler#70]
Sry to bother u！
I have a directory organized as follows
![image](https://github.com/jbehley/point_labeler/assets/42089076/201f6c55-8e46-4f20-bcfa-05e60e29cfbe)
but when I open this dir，the program would show Error below：
terminate called after throwing an instance of 'boost::wrapexcept<boost::bad_lexical_cast>'
  what():  bad lexical cast: source type value could not be interpreted as target
I have no ideas why I occur this problem，could u plz give me some instructions，Thanks a lot！

This is all info the bash show：
##################################
OpenGL Context Version 4.5 core profile
GLEW initialized.
OpenGL context version: 4.5
OpenGL vendor string  : Mesa/X.org
OpenGL renderer string: llvmpipe (LLVM 12.0.0, 256 bits)
temp mem size: 3.6 MB
Found 20 instanceable labels.
-- Setting 'tile size' to 100
mem size: 2400 MB
-- Setting 'max scans' to 500
-- Setting 'min range' to 2.5
-- Setting 'max range' to 50
/opt/point_labler_ws/src/point_labeler/bin
terminate called after throwing an instance of 'boost::wrapexcept<boost::bad_lexical_cast>'
  what():  bad lexical cast: source type value could not be interpreted as target

**Comment by jbehley** [comment]
could you solve the issue by now? It sounds like a problem with the "locale", where numbers are not represented by "XX.YYY" but "XX,YYY"; ensure that your terminal or the context that the code is executed is "en.US" or similar where decimal numbers are represented with a "dot".

**Comment by jbehley** [comment]
Try the following to set the locale: https://www.thomas-krenn.com/en/wiki/Configure_Locales_in_Ubuntu

**Comment by jbehley** [comment]
There has been no update for some time, therefore I closed the issue. If the problem persists, then you can re-open the issue again.
