### ISSUE TITLE
Unable to setup on Ubuntu 20.04LTS

### ISSUE THREAD

**Issue by ashwinjoseph95** [jbehley/point_labeler#76]
Hey Guys!
I was trying to setup the tool by following the instructions provided but at the moment while trying to run the generated binary file ./labeler I am getting a message with Segmentation fault. Any guidance on how to resolve it would be helpful. Thanks!
![Screenshot from 2023-10-30 15-54-32](https://github.com/jbehley/point_labeler/assets/30999857/8db250df-13cd-47d7-bf33-1fc1ae5173f2)

**Comment by jbehley** [comment]
I never had the opportunity to test it on AMD graphics cards, so it might be simply that there is a feature I used that caused the crash.

For diagnosing the problem, I would need to know where the problem happens, i.e., you need to call it with `gdb ./labeler`.
