### ISSUE TITLE
Labeling custom dataset with Velodyne VLP-16

### ISSUE THREAD

**Issue by mathur01** [jbehley/point_labeler#77]
Hi, i am bit new in this domain and using Velodyne VLP-16 lidar to perform custom training on new classes. 
I am able to build this repository and can launch it properly. I am facing issue in getting `calib.txt` and `pose.txt`. From each scan i am able to get `pcap` files which i convert to `bin` format. 
Kindly guide how i can get `calib` and `pose` for each scan. 

Thanks

**Comment by mathur01** [comment]
Thanks for your reply. I spent some time in understanding collection for `pose.txt` and SLAM. Got bit confusing in doing setup. We are not planning to have camera along with LiDAR. Kindly share some links for SLAM in which we can directly get `pose.txt  `.
Thanks in advance.

**Comment by jbehley** [comment]
Please have a look at kiss-icp (https://github.com/PRBonn/kiss-icp), which can provide LiDAR poses; I think  it also can produce KITTI poses or do this with minimal implementation effort.

Therefore, I close the issue for now. If you have further question regarding this issue, please reopen the issue.
