### ISSUE TITLE
Color Pallette of GUI doesn't exist in Ubuntu 20.04LTS

### ISSUE THREAD

**Issue by eren-aydemir** [jbehley/point_labeler#79]
I've succesfully installed all dependencies written in the readme. GUI opens with no problem. Navigation in the cloud is not possible unless I hit to CTRL. Mouse buttons doesn't work except for zooming with wheel. Points tab doesn't has color palette, I cannot paint any point. You can find snapshots from the GUI

![image](https://github.com/jbehley/point_labeler/assets/23127394/7795642c-30e1-4adc-8520-1df674e07a43)

Note: I've started from fresh Ubuntu 20.04LTS installation

**Comment by maaayz87** [comment]
How did you solve it? I also encountered the same problem
