### ISSUE TITLE
Not displaying point cloud after changing tile

### ISSUE THREAD

**Issue by brunoeducsantos** [jbehley/point_labeler#8]
Hi @jbehley ,
Thanks for the amazing tool. 
My issue is after displaying correctly the first point cloud, when changing to other tile it loads but it does not display the cloud.
Any ideas why?
Thanks,
Bruno

**Comment by jbehley** [comment]
Without more information it's hard to guess what is going wrong. But note that not every tile needs to have points. I use only the scan pose and a heuristic to determine if a tile could contain points. It might be that there should be an overlap with the scans, but depending on the distribution it could be that is simply not overlapping with the tile:

![image](https://user-images.githubusercontent.com/11506664/67292338-2a8abe00-f4e3-11e9-82ff-362b616ffeb7.png)


The blue radius is the "overlap heuristic", but the scan outline must not actually overlap with the tile.

However, to help you with debugging the issue, here what I usually try first:
1. I usually first ensure if the draw call is getting by just outputting how many points should be drawn. 

https://github.com/jbehley/point_labeler/blob/769c060138cf091132e01eba348cd457c450c0a8/src/widget/Viewport.cpp#L745

Something like adding `std::cout << points_.size() << std::endl;`  before this condition.
2. If there should be points drawn, the points might have just a "white remission"; you can try to use a different colormap to see high remission points.

![image](https://user-images.githubusercontent.com/11506664/67292464-4d1cd700-f4e3-11e9-982b-95bb3b40f7f3.png)

I hope that helps to check the first issues and better understand the problem.

I suspect that you're using your own data?

**Comment by jbehley** [comment]
@brunoeducsantos is your problem resolved?

**Comment by brunoeducsantos** [comment]
Yes. Sorry for the delay. Thanks
