### ISSUE TITLE
catkin build error

### ISSUE THREAD

**Issue by GuoZheXinDeGuang** [jbehley/point_labeler#80]
Hello! I did every step before the catkin build step correctly, but when I came to the build step, it raised the following  error. I don't know how to solve it. 
![截图 2024-01-08 09-22-22](https://github.com/jbehley/point_labeler/assets/111119930/34f93c37-25c7-46eb-927c-28b881ee5924)

**Comment by jbehley** [comment]
I'm currently working on a more predictable build setup using pure cmake (without catkin).

However, this problem seems to be related to gtest; I just updated the `CMakeList.txt` and it should now compile with the old catkin-based setup.

Could you confirm that it works now on your side?

**Comment by GuoZheXinDeGuang** [comment]
yes it works! Thank you.

**Comment by jbehley** [comment]
Now, you can also try building it without catkin. But as it seems to work now, I close the issue.
