### ISSUE TITLE
Undo button

### ISSUE THREAD

**Issue by zzhuolun** [jbehley/point_labeler#82]
The labeler tool is very powerful! However, I couldn't find the undo feature (i.e. reverse the recent labeling actions). Is this feature not supported in the point labeler?

**Comment by jbehley** [comment]
That would be a good addition that also bothers me for quite some time, but we currently have no plans (nor time) to extend the `point_labeler` with this feature.

**Comment by zzhuolun** [comment]
Thanks for the reply! I found a workaround: using the `unlabeled` class, though it can't entirely replace the `undo` button.

**Comment by jbehley** [comment]
If you just want to remove the class that was last labeled, you can combine also the "non-overwrite" and the "right mouse button" labeling to remove just the class that you added last. Generally, the right mouse button removes the labels when the brush is active.
