### ISSUE TITLE
Issue with Zooming Using the Mouse Wheel

### ISSUE THREAD

**Issue by makucas** [jbehley/point_labeler#84]
Hello,

Our team is working on a research project, and we are using the tool to annotate our point clouds.

Initially, we were all using the tool within the WSL environment. The program worked as expected, but it became slow and heavy depending on the size of the point cloud. So, we decided to install native Ubuntu on the computer and use the tool there.

We managed to install it successfully, but the software presents a strange bug when zooming in on the point cloud using the mouse wheel. It's as if the zoom applies 10 times the normal zoom per wheel movement, both for zooming in and out. We found it very strange since this problem didn’t occur in WSL.

We tried several different alternatives, from reinstalling the program, reducing the mouse wheel sensitivity in the operating system, reinstalling the operating system (both Ubuntu 22 and Ubuntu 24), and these tests were done on four different computers.

The mouse wheel works normally in the operating system, including in some parts of the software itself, as we can increment numerical values such as the threshold of the remove ground feature one by one using the mouse wheel.

**Comment by jbehley** [comment]
Sorry hadn't time to look into it; it's also maybe something in Qt that changed and I have no direct idea how to resolve your issue.

I unfortunately have not the time to do UX improvements as I'm not developing this further and encourage you to change code as needed for your specific use case. There might be also better solutions then changing it.
